<?php

/**
 * Spell Checker Configuration
 * 
 * Từ điển cho spell checker - có thể mở rộng khi có bài học thực tế
 * 
 * TODO: Khi triển khai thực tế, có thể:
 * - Load từ database (table vocabulary hoặc question_keywords)
 * - Load từng bài học (lesson-specific vocabulary)
 * - Dynamic loading từ API
 */

return [
    'hobby' => [
        'actions' => [
            // Common action verbs/gerunds
            'playing', 'play', 'reading', 'read', 'singing', 'sing', 
            'dancing', 'dance', 'drawing', 'draw', 'painting', 'paint',
            'swimming', 'swim', 'cooking', 'cook', 'baking', 'bake',
            'cycling', 'biking', 'ride', 'riding', 'running', 'run', 'jogging',
            'writing', 'write', 'studying', 'study', 'learning', 'learn',
            'watching', 'watch', 'listening', 'listen',
            'gardening', 'garden', 'hiking', 'traveling', 'travel',
            'collecting', 'fishing', 'camping', 'exercising', 'exercise',
            'skating', 'skate', 'jumping', 'jump', 'climbing', 'climb'
        ],
        'objects' => [
            // Common hobby objects/nouns
            'games', 'sports', 'music', 'books', 'cards', 'chess',
            'football', 'soccer', 'basketball', 'tennis', 'volleyball',
            'piano', 'guitar', 'violin', 'drums',
            'photos', 'pictures', 'art', 'movies', 'films',
            'animals', 'pets', 'dogs', 'cats', 'birds',
            'flowers', 'plants', 'trees'
        ]
    ],
    
    // Grammar patterns for common mistakes
    // Format: 'pattern' => 'error_message'
    'grammar_patterns' => [
        // "real" should be "really" before verbs/adjectives
        '/\b(real)\s+(love|like|enjoy|hate|want|need|think|feel|know|see|hear|be|am|is|are|was|were)\b/i' => 'Sử dụng "really" thay vì "real" trước động từ.',
        '/\b(real)\s+(good|bad|nice|great|beautiful|happy|sad|tired|excited)\b/i' => 'Sử dụng "really" thay vì "real" trước tính từ.',
        
        // Missing "to be" verbs (is/are/am/was/were)
        // "It [adjective/noun]" - missing "is" (only at start of sentence or after punctuation)
        // Note: Order matters - more specific patterns should come first
        '/^(it)\s+(sunny|rainy|cloudy|windy|snowy|good|bad|nice|great|beautiful|happy|sad|tired|excited|cold|hot|warm|cool|big|small|new|old|young)\s+(today|tomorrow|yesterday|now|here|there)\b/i' => 'Thiếu động từ "is". Ví dụ: "It is sunny today." hoặc "It\'s sunny today."',
        '/^(it)\s+(sunny|rainy|cloudy|windy|snowy|good|bad|nice|great|beautiful|happy|sad|tired|excited|cold|hot|warm|cool|big|small|new|old|young)\b/i' => 'Thiếu động từ "is". Ví dụ: "It is sunny today." hoặc "It\'s sunny today."',
        '/^(it)\s+([a-z]+)\s+(today|tomorrow|yesterday|now|here|there)\b/i' => 'Thiếu động từ "is". Ví dụ: "It is sunny today." hoặc "It\'s sunny today."',
        
        // "She/He [adjective/noun]" - missing "is" (only at start)
        '/^(she|he)\s+(sunny|rainy|cloudy|windy|snowy|good|bad|nice|great|beautiful|happy|sad|tired|excited|cold|hot|warm|cool|big|small|new|old|young)\b/i' => 'Thiếu động từ "is". Ví dụ: "She is happy." hoặc "He is nice."',
        
        // "They/We [adjective/noun]" - missing "are" (only at start)
        '/^(they|we)\s+(sunny|rainy|cloudy|windy|snowy|good|bad|nice|great|beautiful|happy|sad|tired|excited|cold|hot|warm|cool|big|small|new|old|young)\b/i' => 'Thiếu động từ "are". Ví dụ: "They are happy." hoặc "We are here."',
        
        // "I [adjective/noun]" - missing "am" (only at start)
        '/^(i)\s+(sunny|rainy|cloudy|windy|snowy|good|bad|nice|great|beautiful|happy|sad|tired|excited|cold|hot|warm|cool|big|small|new|old|young)\b/i' => 'Thiếu động từ "am". Ví dụ: "I am happy." hoặc "I\'m happy."',
        
        // Missing modal verbs or "to be" before "be"
        // "Tomorrow/Next/Yesterday + be" - missing "will/is"
        '/\b(tomorrow|next|yesterday|today)\s+(be)\s+/i' => 'Thiếu động từ "will" hoặc "is". Ví dụ: "Tomorrow will be a sunny day." hoặc "Tomorrow is a sunny day."',
        
        // "[Noun/Time] + be" without modal verb - wrong structure (only if not already matched above)
        // Match: "word be" but not "to be", "will be", "can be", etc.
        // Exclude cases where "be" is part of "and be" or other conjunctions
        '/\b(?!tomorrow|next|yesterday|today|to|will|can|could|should|may|might|must|would|am|is|are|was|were|been|being|and|or|but|so|because|if|when|where)([a-z]+)\s+(be)\s+(a|an|the)?\s*[a-z]+/i' => 'Cấu trúc câu sai. "be" cần đi kèm với động từ phù hợp hoặc modal verb. Ví dụ: "will be", "is", "are".',
        
        // Subject-verb agreement errors
        // "weather are" - wrong agreement (weather is singular)
        '/\b(the\s+)?weather\s+(are|were)\b/i' => 'Sai ngữ pháp: "weather" là số ít, cần dùng "is" hoặc "was". Ví dụ: "The weather is sunny."',
        
        // Subject-verb agreement: "She/He + V" (missing -s/-es)
        // "She like" should be "She likes"
        '/\b(she|he)\s+(like|love|want|need|play|go|come|run|walk|eat|drink|sleep|read|write|speak|talk|buy|sell|open|close|start|stop|finish|begin|help|try|use|call|find|keep|leave|put|bring|send|show|meet|feel|become|turn|move|live|stay|wait|return|arrive|happen|change|grow|build|break|cut|draw|fall|fly|hear|hold|learn|lose|pay|prove|remember|set|shoot|sing|teach|throw|understand|wear|win|make|take|give|get|see|know|think|say|tell|ask|look|listen|sit|stand|wake|dance|jump|climb|cook|clean|wash|drive|ride|travel|visit|enjoy|relax|exercise|practice|improve|develop|create|design|paint|explain|forget|choose|decide|plan|expect|hope|wish|dream|imagine|believe|guess|suppose|seem|appear|sound|taste|smell|remain|continue|succeed|fail|beat|defeat|compete|participate|join|attend|organize|prepare|arrange|manage|control|handle|solve|fix|repair|check|test|examine|review|analyze|evaluate|compare|contrast|discuss|debate|argue|agree|disagree|suggest|recommend|advise|warn|remind|inform|notify|announce|declare|claim|state|mention|describe|express|share|communicate|contact|connect|greet|introduce|present|demonstrate|provide|supply|offer|receive|accept|refuse|reject|deny|allow|permit|forbid|prevent|protect|save|rescue|assist|support|encourage|motivate|inspire|influence|affect|impact|progress|advance|achieve|accomplish|complete|quit|abandon)(?!s|ing|ed|en|out|in|on|up|down|off|away|back|together|around|along|through|over|across|by|with|for|at|from|to|into|onto|upon|within|without|behind|beside|between|beyond|under|above|near|far|inside|outside|between|among|during|before|after|while|since|until|unless|because|although|though|if|when|where|why|how|who|what|which|whose|whom|that|this|these|those|them|they|their|there|then|than|the|a|an|and|or|but|so|yet|nor|for|as|of|in|on|at|to|from|by|with|about|into|through|during|including|according|against|among|throughout|despite|towards|upon|concerning)\s+[a-z]/i' => 'Sai ngữ pháp: "She/He" là số ít, động từ cần có "-s" hoặc "-es". Ví dụ: "She likes sunny weather." không phải "She like sunny weather."',
        
        // Subject-verb agreement: "They/We + V + s" (wrong -s/-es)
        // "They likes" should be "They like"
        '/\b(they|we)\s+(likes|loves|wants|needs|plays|goes|comes|runs|walks|eats|drinks|sleeps|reads|writes|speaks|talks|buys|sells|opens|closes|starts|stops|finishes|begins|helps|tries|uses|calls|finds|keeps|leaves|puts|brings|sends|shows|meets|feels|becomes|turns|moves|lives|stays|waits|returns|arrives|happens|changes|grows|builds|breaks|cuts|draws|falls|flies|hears|holds|learns|loses|pays|proves|remembers|sets|shoots|sings|teaches|throws|understands|wears|wins|makes|takes|gives|gets|sees|knows|thinks|says|tells|asks|looks|listens|sits|stands|wakes|dances|jumps|climbs|cooks|cleans|washes|drives|rides|travels|visits|enjoys|relaxes|exercises|practices|improves|develops|creates|designs|paints|explains|forgets|chooses|decides|plans|expects|hopes|wishes|dreams|imagines|believes|guesses|supposes|seems|appears|sounds|tastes|smells|remains|continues|succeeds|fails|beats|defeats|competes|participates|joins|attends|organizes|prepares|arranges|manages|controls|handles|solves|fixes|repairs|checks|tests|examines|reviews|analyzes|evaluates|compares|contrasts|discusses|debates|argues|agrees|disagrees|suggests|recommends|advises|warns|reminds|informs|notifies|announces|declares|claims|states|mentions|describes|expresses|shares|communicates|contacts|connects|greets|introduces|presents|demonstrates|provides|supplies|offers|receives|accepts|refuses|rejects|denies|allows|permits|forbids|prevents|protects|saves|rescues|assists|supports|encourages|motivates|inspires|influences|affects|impacts|progresses|advances|achieves|accomplishes|completes|quits|abandons)\s+[a-z]/i' => 'Sai ngữ pháp: "They/We" là số nhiều, động từ không có "-s" hoặc "-es". Ví dụ: "They like sunny weather." không phải "They likes sunny weather."',
        
        // Invalid adjective forms (adding -ing to adjectives)
        // "sunnying", "happying", etc.
        '/\b(sunny|rainy|cloudy|windy|snowy|happy|sad|tired|excited|good|bad|nice|great|beautiful|big|small|new|old|young|warm|cool)\s*(ing)\b/i' => 'Tính từ không thể thêm "-ing". Ví dụ: "sunny" không thể là "sunnying".',
        '/\b(sunny|rainy|cloudy|windy|snowy|happy|sad|tired|excited|good|bad|nice|great|beautiful|big|small|new|old|young|warm|cool)ing\b/i' => 'Tính từ không thể thêm "-ing". Ví dụ: "sunny" không thể là "sunnying".',
        
        // "want to + V-ing" - wrong infinitive form
        // Should be "want to + V" (infinitive), not "want to + V-ing"
        '/\b(want|wants|wanted|need|needs|needed|like|likes|liked|love|loves|loved|try|tries|tried|plan|plans|planned|hope|hopes|hoped|decide|decides|decided|expect|expects|expected)\s+to\s+[a-z]+ing\b/i' => 'Sau "want to", "need to", "like to" cần dùng động từ nguyên mẫu (không có -ing). Ví dụ: "I want to swim" không phải "I want to swimming".',
        
        // "be + V" without -ing (present continuous)
        // "I'm hangout" should be "I'm hanging out" or "I hang out"
        // Match specific common verbs that commonly appear without -ing
        '/\b(am|is|are|was|were|i\'m|you\'re|he\'s|she\'s|it\'s|we\'re|they\'re)\s+(hangout|hang|swim|go|come|run|walk|play|work|study|eat|drink|sleep|read|write|speak|talk|buy|sell|open|close|start|stop|finish|begin|help|try|use|call|find|keep|leave|put|bring|send|show|meet|feel|become|turn|move|live|stay|wait|return|arrive|happen|change|grow|build|break|cut|draw|fall|fly|hear|hold|learn|lose|pay|prove|remember|set|shoot|sing|teach|throw|understand|wear|win|make|take|give|get|see|know|think|say|tell|ask|want|need|like|love|hate|look|listen|sit|stand|wake|dance|jump|climb|cook|clean|wash|drive|ride|travel|visit|enjoy|relax|exercise|practice|improve|develop|create|design|paint|explain|forget|choose|decide|plan|expect|hope|wish|dream|imagine|believe|guess|suppose|seem|appear|sound|taste|smell|remain|continue|succeed|fail|beat|defeat|compete|participate|join|attend|organize|prepare|arrange|manage|control|handle|solve|fix|repair|check|test|examine|review|analyze|evaluate|compare|contrast|discuss|debate|argue|agree|disagree|suggest|recommend|advise|warn|remind|inform|notify|announce|declare|claim|state|mention|describe|express|share|communicate|contact|connect|greet|introduce|present|demonstrate|provide|supply|offer|receive|accept|refuse|reject|deny|allow|permit|forbid|prevent|protect|save|rescue|assist|support|encourage|motivate|inspire|influence|affect|impact|progress|advance|achieve|accomplish|complete|quit|abandon)(?!ing|out|in|on|up|down|off|away|back|together|around|along|through|over|across|by|with|for|at|from|to|into|onto|upon|within|without|behind|beside|between|beyond|under|above|near|far|inside|outside|between|among|during|before|after|while|since|until|unless|because|although|though|if|when|where|why|how|who|what|which|whose|whom|that|this|these|those|them|they|their|there|then|than|the|a|an|and|or|but|so|yet|nor|for|as|of|in|on|at|to|from|by|with|about|into|through|during|including|according|against|among|throughout|despite|towards|upon|concerning|ed|en|s)\s+[a-z]/i' => 'Sau "am/is/are/was/were", động từ cần có "-ing" (present continuous). Ví dụ: "I am hanging out" hoặc "I hang out", không phải "I am hangout".',
        
        // "a" vs "an" before vowels (basic check)
        // Note: This is a simple check, might have false positives
        // '/\ba\s+[aeiou]/i' => 'Kiểm tra lại "a" hoặc "an" trước nguyên âm.',
        
        // Common verb tense errors (basic patterns)
        // '/\b(go|come|do|have|be)\s+(ed|ing)\b/i' => 'Kiểm tra lại thì của động từ.',
        
        // Double negatives
        // '/\b(no|not|never)\s+.*\b(no|not|never)\b/i' => 'Tránh dùng phủ định kép.',
    ],
    
    // Có thể thêm các category khác khi có bài học mới
    // 'location' => [...],
    // 'weather' => [...],
    // 'food' => [...],
    
    // Simple English-Vietnamese dictionary (fallback)
    'translations' => [
        // Common verbs
        'playing' => 'chơi',
        'play' => 'chơi',
        'reading' => 'đọc',
        'read' => 'đọc',
        'singing' => 'hát',
        'sing' => 'hát',
        'dancing' => 'nhảy',
        'dance' => 'nhảy',
        'drawing' => 'vẽ',
        'draw' => 'vẽ',
        'swimming' => 'bơi',
        'swim' => 'bơi',
        'cooking' => 'nấu ăn',
        'cook' => 'nấu ăn',
        'writing' => 'viết',
        'write' => 'viết',
        'learning' => 'học',
        'learn' => 'học',
        'studying' => 'học',
        'study' => 'học',
        'watching' => 'xem',
        'watch' => 'xem',
        'listening' => 'nghe',
        'listen' => 'nghe',
        'speaking' => 'nói',
        'speak' => 'nói',
        'talking' => 'nói',
        'talk' => 'nói',
        'saying' => 'nói',
        'say' => 'nói',
        'going' => 'đi',
        'go' => 'đi',
        'coming' => 'đến',
        'come' => 'đến',
        'doing' => 'làm',
        'do' => 'làm',
        'making' => 'làm',
        'make' => 'làm',
        'seeing' => 'thấy',
        'see' => 'thấy',
        'knowing' => 'biết',
        'know' => 'biết',
        'thinking' => 'nghĩ',
        'think' => 'nghĩ',
        'living' => 'sống',
        'live' => 'sống',
        'working' => 'làm việc',
        'work' => 'làm việc',
        'eating' => 'ăn',
        'eat' => 'ăn',
        'drinking' => 'uống',
        'drink' => 'uống',
        'sleeping' => 'ngủ',
        'sleep' => 'ngủ',
        'getting' => 'nhận',
        'get' => 'nhận',
        'giving' => 'cho',
        'give' => 'cho',
        'taking' => 'lấy',
        'take' => 'lấy',
        'using' => 'sử dụng',
        'use' => 'sử dụng',
        'having' => 'có',
        'have' => 'có',
        'wanting' => 'muốn',
        'want' => 'muốn',
        'liking' => 'thích',
        'like' => 'thích',
        'loving' => 'yêu',
        'love' => 'yêu',
        'needing' => 'cần',
        'need' => 'cần',
        
        // Common nouns
        'games' => 'trò chơi',
        'game' => 'trò chơi',
        'music' => 'âm nhạc',
        'books' => 'sách',
        'book' => 'sách',
        'sports' => 'thể thao',
        'sport' => 'thể thao',
        'hobby' => 'sở thích',
        'hobbies' => 'sở thích',
        'question' => 'câu hỏi',
        'questions' => 'câu hỏi',
        'answer' => 'câu trả lời',
        'answers' => 'câu trả lời',
        'sentence' => 'câu',
        'sentences' => 'câu',
        'word' => 'từ',
        'words' => 'từ',
        'complete' => 'hoàn thành',
        'using' => 'sử dụng',
        'given' => 'cho sẵn',
        'instruction' => 'hướng dẫn',
        'instructions' => 'hướng dẫn',
        'prompt' => 'đề bài',
        'prompts' => 'đề bài',
        'exercise' => 'bài tập',
        'exercises' => 'bài tập',
        'lesson' => 'bài học',
        'lessons' => 'bài học',
        'unit' => 'bài',
        'units' => 'bài',
        'topic' => 'chủ đề',
        'topics' => 'chủ đề',
        'subject' => 'môn học',
        'subjects' => 'môn học',
        'teacher' => 'giáo viên',
        'teachers' => 'giáo viên',
        'student' => 'học sinh',
        'students' => 'học sinh',
        'school' => 'trường học',
        'schools' => 'trường học',
        'class' => 'lớp',
        'classes' => 'lớp',
        'homework' => 'bài tập về nhà',
        'homework' => 'bài tập về nhà',
        'test' => 'bài kiểm tra',
        'tests' => 'bài kiểm tra',
        'exam' => 'bài thi',
        'exams' => 'bài thi',
        
        // Personal pronouns and common words
        'my' => 'của tôi',
        'your' => 'của bạn',
        'his' => 'của anh ấy',
        'her' => 'của cô ấy',
        'our' => 'của chúng tôi',
        'their' => 'của họ',
        'i' => 'tôi',
        'you' => 'bạn',
        'he' => 'anh ấy',
        'she' => 'cô ấy',
        'we' => 'chúng tôi',
        'they' => 'họ',
        'it' => 'nó',
        'this' => 'này',
        'that' => 'kia',
        'these' => 'những cái này',
        'those' => 'những cái kia',
        
        // Common adjectives
        'favorite' => 'yêu thích',
        'favourite' => 'yêu thích',
        'good' => 'tốt',
        'nice' => 'tốt',
        'great' => 'tuyệt vời',
        'wonderful' => 'tuyệt vời',
        'beautiful' => 'đẹp',
        'pretty' => 'đẹp',
        'big' => 'lớn',
        'small' => 'nhỏ',
        'large' => 'lớn',
        'little' => 'nhỏ',
        'long' => 'dài',
        'short' => 'ngắn',
        'new' => 'mới',
        'old' => 'cũ',
        'young' => 'trẻ',
        'happy' => 'vui',
        'sad' => 'buồn',
        'tired' => 'mệt',
        'excited' => 'phấn khích',
        'interested' => 'quan tâm',
        'interesting' => 'thú vị',
        
        // Common verbs
        'is' => 'là',
        'are' => 'là',
        'was' => 'là',
        'were' => 'là',
        'am' => 'là',
        'be' => 'là',
        'been' => 'là',
        'being' => 'là',
        'has' => 'có',
        'had' => 'có',
        'does' => 'làm',
        'did' => 'làm',
        'done' => 'làm xong',
        'will' => 'sẽ',
        'would' => 'sẽ',
        'can' => 'có thể',
        'could' => 'có thể',
        'should' => 'nên',
        'must' => 'phải',
        'may' => 'có thể',
        'might' => 'có thể',
        
        // Common prepositions and conjunctions
        'in' => 'ở',
        'on' => 'trên',
        'at' => 'tại',
        'to' => 'đến',
        'from' => 'từ',
        'with' => 'với',
        'by' => 'bởi',
        'for' => 'cho',
        'of' => 'của',
        'about' => 'về',
        'into' => 'vào',
        'onto' => 'lên',
        'up' => 'lên',
        'down' => 'xuống',
        'over' => 'qua',
        'under' => 'dưới',
        'above' => 'ở trên',
        'below' => 'ở dưới',
        'between' => 'giữa',
        'among' => 'giữa',
        'through' => 'qua',
        'during' => 'trong khi',
        'before' => 'trước',
        'after' => 'sau',
        'since' => 'từ khi',
        'until' => 'cho đến khi',
        'while' => 'trong khi',
        'and' => 'và',
        'or' => 'hoặc',
        'but' => 'nhưng',
        'so' => 'vì vậy',
        'because' => 'bởi vì',
        'if' => 'nếu',
        'when' => 'khi',
        'where' => 'ở đâu',
        'why' => 'tại sao',
        'how' => 'như thế nào',
        'what' => 'cái gì',
        'who' => 'ai',
        'which' => 'cái nào',
        'whose' => 'của ai',
        
        // Common nouns (time and daily life)
        'name' => 'tên',
        'names' => 'tên',
        'age' => 'tuổi',
        'years' => 'tuổi',
        'year' => 'năm',
        'month' => 'tháng',
        'months' => 'tháng',
        'week' => 'tuần',
        'weeks' => 'tuần',
        'day' => 'ngày',
        'days' => 'ngày',
        'today' => 'hôm nay',
        'tomorrow' => 'ngày mai',
        'yesterday' => 'hôm qua',
        'morning' => 'buổi sáng',
        'afternoon' => 'buổi chiều',
        'evening' => 'buổi tối',
        'night' => 'đêm',
        'time' => 'thời gian',
        'times' => 'lần',
        'hour' => 'giờ',
        'hours' => 'giờ',
        'minute' => 'phút',
        'minutes' => 'phút',
        'second' => 'giây',
        'seconds' => 'giây',
        'now' => 'bây giờ',
        'then' => 'sau đó',
        'today' => 'hôm nay',
        'tomorrow' => 'ngày mai',
        'yesterday' => 'hôm qua',
        
        // Greetings
        'hello' => 'xin chào',
        'hi' => 'chào',
        'hey' => 'này',
        'goodbye' => 'tạm biệt',
        'bye' => 'tạm biệt',
        'thanks' => 'cảm ơn',
        'thank' => 'cảm ơn',
        'please' => 'xin vui lòng',
        'sorry' => 'xin lỗi',
        'excuse' => 'xin lỗi',
        'welcome' => 'chào mừng',
        'nice' => 'tốt',
        'meet' => 'gặp',
        'meeting' => 'cuộc gặp',
        
        // Family
        'family' => 'gia đình',
        'families' => 'gia đình',
        'father' => 'bố',
        'dad' => 'bố',
        'mother' => 'mẹ',
        'mom' => 'mẹ',
        'parents' => 'bố mẹ',
        'parent' => 'cha mẹ',
        'brother' => 'anh trai',
        'sister' => 'chị gái',
        'siblings' => 'anh chị em',
        'sibling' => 'anh chị em',
        'son' => 'con trai',
        'daughter' => 'con gái',
        'children' => 'trẻ em',
        'child' => 'trẻ em',
        'baby' => 'em bé',
        'babies' => 'em bé',
        'grandfather' => 'ông',
        'grandmother' => 'bà',
        'grandpa' => 'ông',
        'grandma' => 'bà',
        'uncle' => 'chú',
        'aunt' => 'cô',
        'cousin' => 'anh chị em họ',
        'cousins' => 'anh chị em họ',
        
        // Body parts
        'head' => 'đầu',
        'hair' => 'tóc',
        'face' => 'mặt',
        'eye' => 'mắt',
        'eyes' => 'mắt',
        'nose' => 'mũi',
        'mouth' => 'miệng',
        'ear' => 'tai',
        'ears' => 'tai',
        'hand' => 'tay',
        'hands' => 'tay',
        'finger' => 'ngón tay',
        'fingers' => 'ngón tay',
        'arm' => 'cánh tay',
        'arms' => 'cánh tay',
        'leg' => 'chân',
        'legs' => 'chân',
        'foot' => 'bàn chân',
        'feet' => 'bàn chân',
        'toe' => 'ngón chân',
        'toes' => 'ngón chân',
        'body' => 'cơ thể',
        'bodies' => 'cơ thể',
        
        // Food
        'food' => 'thức ăn',
        'foods' => 'thức ăn',
        'meal' => 'bữa ăn',
        'meals' => 'bữa ăn',
        'breakfast' => 'bữa sáng',
        'lunch' => 'bữa trưa',
        'dinner' => 'bữa tối',
        'snack' => 'đồ ăn nhẹ',
        'snacks' => 'đồ ăn nhẹ',
        'water' => 'nước',
        'milk' => 'sữa',
        'juice' => 'nước ép',
        'bread' => 'bánh mì',
        'rice' => 'cơm',
        'noodles' => 'mì',
        'noodle' => 'mì',
        'meat' => 'thịt',
        'fish' => 'cá',
        'chicken' => 'gà',
        'beef' => 'thịt bò',
        'pork' => 'thịt lợn',
        'egg' => 'trứng',
        'eggs' => 'trứng',
        'fruit' => 'trái cây',
        'fruits' => 'trái cây',
        'apple' => 'táo',
        'apples' => 'táo',
        'banana' => 'chuối',
        'bananas' => 'chuối',
        'orange' => 'cam',
        'oranges' => 'cam',
        'vegetable' => 'rau',
        'vegetables' => 'rau',
        
        // Colors
        'color' => 'màu',
        'colors' => 'màu',
        'colour' => 'màu',
        'colours' => 'màu',
        'red' => 'đỏ',
        'blue' => 'xanh dương',
        'green' => 'xanh lá',
        'yellow' => 'vàng',
        'orange' => 'cam',
        'purple' => 'tím',
        'pink' => 'hồng',
        'brown' => 'nâu',
        'black' => 'đen',
        'white' => 'trắng',
        'grey' => 'xám',
        'gray' => 'xám',
        
        // Numbers
        'one' => 'một',
        'two' => 'hai',
        'three' => 'ba',
        'four' => 'bốn',
        'five' => 'năm',
        'six' => 'sáu',
        'seven' => 'bảy',
        'eight' => 'tám',
        'nine' => 'chín',
        'ten' => 'mười',
        'eleven' => 'mười một',
        'twelve' => 'mười hai',
        'thirteen' => 'mười ba',
        'fourteen' => 'mười bốn',
        'fifteen' => 'mười lăm',
        'sixteen' => 'mười sáu',
        'seventeen' => 'mười bảy',
        'eighteen' => 'mười tám',
        'nineteen' => 'mười chín',
        'twenty' => 'hai mươi',
        'thirty' => 'ba mươi',
        'forty' => 'bốn mươi',
        'fifty' => 'năm mươi',
        'sixty' => 'sáu mươi',
        'seventy' => 'bảy mươi',
        'eighty' => 'tám mươi',
        'ninety' => 'chín mươi',
        'hundred' => 'trăm',
        'thousand' => 'nghìn',
        'million' => 'triệu',
        'first' => 'đầu tiên',
        'second' => 'thứ hai',
        'third' => 'thứ ba',
        'fourth' => 'thứ tư',
        'fifth' => 'thứ năm',
        
        // Places
        'place' => 'nơi',
        'places' => 'nơi',
        'house' => 'nhà',
        'houses' => 'nhà',
        'home' => 'nhà',
        'homes' => 'nhà',
        'room' => 'phòng',
        'rooms' => 'phòng',
        'bedroom' => 'phòng ngủ',
        'bathroom' => 'phòng tắm',
        'kitchen' => 'nhà bếp',
        'living' => 'phòng khách',
        'garden' => 'vườn',
        'gardens' => 'vườn',
        'park' => 'công viên',
        'parks' => 'công viên',
        'school' => 'trường học',
        'schools' => 'trường học',
        'hospital' => 'bệnh viện',
        'hospitals' => 'bệnh viện',
        'store' => 'cửa hàng',
        'stores' => 'cửa hàng',
        'shop' => 'cửa hàng',
        'shops' => 'cửa hàng',
        'restaurant' => 'nhà hàng',
        'restaurants' => 'nhà hàng',
        'library' => 'thư viện',
        'libraries' => 'thư viện',
        'zoo' => 'sở thú',
        'zoos' => 'sở thú',
        'beach' => 'bãi biển',
        'beaches' => 'bãi biển',
        'mountain' => 'núi',
        'mountains' => 'núi',
        'river' => 'sông',
        'rivers' => 'sông',
        'lake' => 'hồ',
        'lakes' => 'hồ',
        'sea' => 'biển',
        'ocean' => 'đại dương',
        'city' => 'thành phố',
        'cities' => 'thành phố',
        'town' => 'thị trấn',
        'towns' => 'thị trấn',
        'village' => 'làng',
        'villages' => 'làng',
        'country' => 'đất nước',
        'countries' => 'đất nước',
        'world' => 'thế giới',
        'countries' => 'các nước',
        
        // Animals
        'animal' => 'động vật',
        'animals' => 'động vật',
        'pet' => 'thú cưng',
        'pets' => 'thú cưng',
        'dog' => 'chó',
        'dogs' => 'chó',
        'cat' => 'mèo',
        'cats' => 'mèo',
        'bird' => 'chim',
        'birds' => 'chim',
        'fish' => 'cá',
        'rabbit' => 'thỏ',
        'rabbits' => 'thỏ',
        'hamster' => 'chuột hamster',
        'hamsters' => 'chuột hamster',
        'turtle' => 'rùa',
        'turtles' => 'rùa',
        'elephant' => 'voi',
        'elephants' => 'voi',
        'lion' => 'sư tử',
        'lions' => 'sư tử',
        'tiger' => 'hổ',
        'tigers' => 'hổ',
        'bear' => 'gấu',
        'bears' => 'gấu',
        'monkey' => 'khỉ',
        'monkeys' => 'khỉ',
        'horse' => 'ngựa',
        'horses' => 'ngựa',
        'cow' => 'bò',
        'cows' => 'bò',
        'pig' => 'lợn',
        'pigs' => 'lợn',
        'sheep' => 'cừu',
        'goat' => 'dê',
        'goats' => 'dê',
        'duck' => 'vịt',
        'ducks' => 'vịt',
        'chicken' => 'gà',
        'chickens' => 'gà',
        'rooster' => 'gà trống',
        'roosters' => 'gà trống',
        
        // Weather
        'weather' => 'thời tiết',
        'sunny' => 'nắng',
        'rainy' => 'mưa',
        'cloudy' => 'có mây',
        'windy' => 'có gió',
        'snowy' => 'có tuyết',
        'snow' => 'tuyết',
        'rain' => 'mưa',
        'sun' => 'mặt trời',
        'cloud' => 'mây',
        'clouds' => 'mây',
        'wind' => 'gió',
        'storm' => 'bão',
        'storms' => 'bão',
        'thunder' => 'sấm',
        'lightning' => 'sét',
        'hot' => 'nóng',
        'cold' => 'lạnh',
        'warm' => 'ấm',
        'cool' => 'mát',
        'temperature' => 'nhiệt độ',
        'temperatures' => 'nhiệt độ',
        
        // Clothes
        'clothes' => 'quần áo',
        'clothing' => 'quần áo',
        'shirt' => 'áo sơ mi',
        'shirts' => 'áo sơ mi',
        'pants' => 'quần',
        'trousers' => 'quần',
        'dress' => 'váy',
        'dresses' => 'váy',
        'skirt' => 'váy',
        'skirts' => 'váy',
        'shoes' => 'giày',
        'shoe' => 'giày',
        'socks' => 'tất',
        'sock' => 'tất',
        'hat' => 'mũ',
        'hats' => 'mũ',
        'cap' => 'mũ lưỡi trai',
        'caps' => 'mũ lưỡi trai',
        'jacket' => 'áo khoác',
        'jackets' => 'áo khoác',
        'coat' => 'áo khoác',
        'coats' => 'áo khoác',
        'scarf' => 'khăn quàng',
        'scarves' => 'khăn quàng',
        'gloves' => 'găng tay',
        'glove' => 'găng tay',
        
        // Transportation
        'car' => 'xe hơi',
        'cars' => 'xe hơi',
        'bus' => 'xe buýt',
        'buses' => 'xe buýt',
        'train' => 'tàu hỏa',
        'trains' => 'tàu hỏa',
        'bike' => 'xe đạp',
        'bikes' => 'xe đạp',
        'bicycle' => 'xe đạp',
        'bicycles' => 'xe đạp',
        'motorcycle' => 'xe máy',
        'motorcycles' => 'xe máy',
        'scooter' => 'xe tay ga',
        'scooters' => 'xe tay ga',
        'plane' => 'máy bay',
        'planes' => 'máy bay',
        'airplane' => 'máy bay',
        'airplanes' => 'máy bay',
        'boat' => 'thuyền',
        'boats' => 'thuyền',
        'ship' => 'tàu',
        'ships' => 'tàu',
        'taxi' => 'taxi',
        'taxis' => 'taxi',
        'truck' => 'xe tải',
        'trucks' => 'xe tải',
        
        // Common phrases
        'how' => 'như thế nào',
        'many' => 'nhiều',
        'much' => 'nhiều',
        'some' => 'một số',
        'any' => 'bất kỳ',
        'all' => 'tất cả',
        'both' => 'cả hai',
        'each' => 'mỗi',
        'every' => 'mọi',
        'few' => 'ít',
        'more' => 'thêm',
        'most' => 'hầu hết',
        'other' => 'khác',
        'another' => 'khác',
        'such' => 'như vậy',
        'only' => 'chỉ',
        'just' => 'chỉ',
        'also' => 'cũng',
        'too' => 'cũng',
        'very' => 'rất',
        'really' => 'thực sự',
        'quite' => 'khá',
        'enough' => 'đủ',
        'still' => 'vẫn',
        'already' => 'đã',
        'yet' => 'chưa',
        'again' => 'lại',
        'once' => 'một lần',
        'twice' => 'hai lần',
        'always' => 'luôn luôn',
        'usually' => 'thường',
        'often' => 'thường',
        'sometimes' => 'đôi khi',
        'rarely' => 'hiếm khi',
        'never' => 'không bao giờ',
        'today' => 'hôm nay',
        'tomorrow' => 'ngày mai',
        'yesterday' => 'hôm qua',
        'here' => 'ở đây',
        'there' => 'ở đó',
        'where' => 'ở đâu',
        'everywhere' => 'mọi nơi',
        'somewhere' => 'đâu đó',
        'anywhere' => 'bất cứ đâu',
        'nowhere' => 'không đâu',
        'way' => 'cách',
        'ways' => 'cách',
        'right' => 'đúng',
        'wrong' => 'sai',
        'true' => 'đúng',
        'false' => 'sai',
        'yes' => 'có',
        'no' => 'không',
        'not' => 'không',
        'yes' => 'đúng',
        'ok' => 'được',
        'okay' => 'được',
        'sure' => 'chắc chắn',
        'maybe' => 'có thể',
        'probably' => 'có lẽ',
        'definitely' => 'chắc chắn',
        'absolutely' => 'hoàn toàn',
        'certainly' => 'chắc chắn',
        'exactly' => 'chính xác',
        'almost' => 'gần như',
        'nearly' => 'gần như',
        'about' => 'khoảng',
        'around' => 'khoảng',
        'approximately' => 'khoảng',
        'almost' => 'gần như',
        'nearly' => 'gần như',
        'exactly' => 'chính xác',
        'just' => 'vừa',
        'only' => 'chỉ',
        'even' => 'thậm chí',
        'especially' => 'đặc biệt',
        'mainly' => 'chủ yếu',
        'mostly' => 'hầu hết',
        'particularly' => 'đặc biệt',
        'probably' => 'có lẽ',
        'perhaps' => 'có lẽ',
        'maybe' => 'có thể',
        'possibly' => 'có thể',
        'certainly' => 'chắc chắn',
        'definitely' => 'chắc chắn',
        'absolutely' => 'hoàn toàn',
        'completely' => 'hoàn toàn',
        'totally' => 'hoàn toàn',
        'entirely' => 'hoàn toàn',
        'quite' => 'khá',
        'rather' => 'khá',
        'fairly' => 'khá',
        'pretty' => 'khá',
        'very' => 'rất',
        'really' => 'thực sự',
        'extremely' => 'cực kỳ',
        'incredibly' => 'cực kỳ',
        'absolutely' => 'hoàn toàn',
        'completely' => 'hoàn toàn',
        'totally' => 'hoàn toàn',
        'quite' => 'khá',
        'rather' => 'khá',
        'fairly' => 'khá',
        'pretty' => 'khá',
        'very' => 'rất',
        'really' => 'thực sự',
        'extremely' => 'cực kỳ',
        'incredibly' => 'cực kỳ',
        'absolutely' => 'hoàn toàn',
        'completely' => 'hoàn toàn',
        'totally' => 'hoàn toàn',
        'quite' => 'khá',
        'rather' => 'khá',
        'fairly' => 'khá',
        'pretty' => 'khá',
        'very' => 'rất',
        'really' => 'thực sự',
        'extremely' => 'cực kỳ',
        'incredibly' => 'cực kỳ',
        'absolutely' => 'hoàn toàn',
        'completely' => 'hoàn toàn',
        'totally' => 'hoàn toàn',
        'quite' => 'khá',
        'rather' => 'khá',
        'fairly' => 'khá',
        'pretty' => 'khá',
        'very' => 'rất',
        'really' => 'thực sự',
        'extremely' => 'cực kỳ',
        'incredibly' => 'cực kỳ',
    ],
];
